vich_uploader:
    db_driver: orm

    mappings:
        profile_picture:
            uri_prefix: /images/pictures
            upload_destination: '%kernel.project_dir%/public/images/pictures'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 50 }
            delete_on_remove: true